### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Rift3000** [Flutter-Buddies/Your-Destiny#10]
We need individuals to Localize the app in a few langauges

**Comment by Goober0329** [comment]
I can help with Spanish localization, but I don't know the first thing about localizing an app yet. I think I'll wait to see how someone else does it and then I can follow their lead.

**Comment by Tragikomedia** [comment]
I will attempt to add a Polish localization for what we already have tomorrow, I did such things in the past, so I should manage (I hope).
