### ISSUE TITLE
Implement a settings Page

### ISSUE THREAD

**Issue by Rift3000** [Flutter-Buddies/Your-Destiny#18]

**Comment by hanskokx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Your Destiny] Add settings screen](https://trello.com/c/VpxfoW35/7-your-destiny-add-settings-screen)

**Comment by ion05** [comment]
What exactly do we want in the settings page ?

**Comment by Rift3000** [comment]
Great settings page
