### ISSUE TITLE
Create A Splash Screen

### ISSUE THREAD

**Issue by Rift3000** [Flutter-Buddies/Your-Destiny#3]
A cool looking screen to display when the app is opened. This screen can have a logo or name displayed for a few seconds before getting to the app. Here is an example of a Splash Screen https://miro.medium.com/max/3364/1*c1x9MdbER2Ol7WLdOIIcyA.jpeg

**Comment by ion05** [comment]
Is the app making a connection to the internet ?

**Comment by Rift3000** [comment]
No internet connection

**Comment by ion05** [comment]
Ok , can i work on this issue ?

**Comment by Rift3000** [comment]
Sure you can work on the Splash Screen

**Comment by ion05** [comment]
No , i meant assign me the issue pls

**Comment by Rift3000** [comment]
Ohhhh sure go ahead.

**Comment by Rift3000** [comment]
The Splash Screen is yours to work on

**Comment by Rift3000** [comment]
In order to really contribute you need to join the Group 10 Flutter Buddies channel in the discord server. That way we can communicate easier.
