### ISSUE TITLE
Destroy All Humans

### ISSUE THREAD

**Issue by Rift3000** [Flutter-Buddies/Your-Destiny#34]
Take me to your leader

**Comment by Rift3000** [comment]
I am your leader

**Comment by Rift3000** [comment]
Our code shall appease the aliens

**Comment by Rift3000** [comment]
No, you must not give the aliens code, they are too powerful

**Comment by Rift3000** [comment]
Mission complete, we aliens now know how to code. You humans stand no chance.

**Comment by hanskokx** [comment]
I, for one, welcome our new alien overlords.
