### ISSUE TITLE
Create a Menu for multiple Story Lines

### ISSUE THREAD

**Issue by Rift3000** [Flutter-Buddies/Your-Destiny#5]
After opening the app the user will see a menu whereby they will choose which story they would like to experience. Example of a simple menu: https://www.windowscentral.com/sites/wpcentral.com/files/styles/xlarge/public/postimages/2014/07/Anagrambles_Menu.jpg?itok=jINCV-wK

**Comment by Tragikomedia** [comment]
By story, do you mean a "story" as in the story brain (one part of the bigger tale, like a scene in the hitchhiking story) or rather as a choosing a "big" story (let's say there will be a hitchhiking story, a sci-fi story, a fantasy story etc.)?

**Comment by Rift3000** [comment]
By "story" I mean that there will be different stories. The hitchhiking story can remain one, we can add a sci-fi story and a fantasy story as well. So lets say we go with a Sci-fi Story; it would be set up in the same manner as the hitchhiking story. There would be choices that lead to a particular conclusion.

**Comment by Rift3000** [comment]
Brilliant
