### ISSUE TITLE
Story Writers/Editors

### ISSUE THREAD

**Issue by Rift3000** [Flutter-Buddies/Your-Destiny#6]
Create cool stories for the app. You can completely change the story and come up with new stories (there will be multiple stories in the app let's aim for 3).

**Comment by Goober0329** [comment]
I'll work on this. I'll also try to work on the choice to page logic when a choice is made.

**Comment by Rift3000** [comment]
Ok I will also help out with creating the story. Welcome fellow writer

**Comment by Rift3000** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Your Destiny] Add another story (or two!)](https://trello.com/c/aUFGH7B5/6-your-destiny-add-another-story-or-two)

**Comment by Rift3000** [comment]
Excellent
